### PR TITLE
Update bower.json

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by rwjblue** [comment]
I locked to a sha in https://github.com/eviltrout/ember-performance/pull/100 due to Benchmark.Suite global being undefined. 

Can you confirm that you can run all of he suites after a nombom with this change?

**Comment by stefanpenner** [comment]
That sha is no longer available. So we will need to o.find one that is.

But no I did not test each benchmark, will try that this morning.

**Comment by rwjblue** [comment]
Ugh.  OK, sorry for the hassle. I didn't have time back then to see what exactly broke the global export for `Benchmark.Suite` (which we use)...

**Comment by rwjblue** [comment]
Was fixed by a9a611bbf0f7094e518b6400f0e4c6c17e728338

**Pull request closed without merging**
